linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - revive
    - prealloc
    - unconvert
    - gocritic

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters

  gofmt:
    simplify: true
